---
# Semantic Versioning 2.0.0
- name: "major"
  color: b60205
  description: "Incompatible API changes or breaks backward compatibility for users"

- name: "minor"
  color: 0e8a16
  description: "Add functionality in a backwards compatible manner"

- name: "patch"
  color: C2E0C6
  description: "Backwards compatible bug fixes"

# Priority
- name: "priority-critical"
  color: ee0701
  description: "Must be addressed as soon as possible."

- name: "priority-high"
  color: b60205
  description: "After critical issues are fixed, these should be dealt with before any further issues."

- name: "priority-medium"
  color: D53B33
  description: "This issue may be useful, and needs some attention."

- name: "priority-low"
  color: e4ea8a
  description: "Nice addition, maybe... someday..."

# Scope
- name: "documentation"
  color: 0052cc
  description: "Improvements or additions to documentation"

- name: "enhancement"
  color: a2eeef
  description: "Enhancement of the code, Refactor, not introducing new features."

- name: "bug"
  color: d73a4a
  description: "Something isn't working"

- name: "performance"
  color: 5E4BDC
  description: "Improving performance of the project, not introducing new features."

- name: "new-feature"
  color: 07A297
  description: "New features or options."

- name: "security"
  color: ee0701
  description: "Addressing a vulnerability or security risk in this project."

# Status
- name: "duplicate"
  color: cfd3d7
  description: "This issue or pull request already exists"

- name: "in-progress"
  color: fbca04
  description: "Issue is currently being worked on by a developer."

- name: "stale"
  color: cfd3d7
  description: "No activity for quite some time."

- name: "incomplete"
  color: B5EEB0
  description: "Missing information."

- name: "invalid"
  color: F25D8F
  description: "This is off-topic, spam, or otherwise doesn't apply to this project."

- name: "wontfix"
  color: ffffff
  description: "This will not be worked on"

# Contributors
- name: "good first issue"
  color: 7057ff
  description: "Good first issue for people wanting to contribute to this project."

- name: "help-wanted"
  color: 008672
  description: "Extra attention is needed"
