---
name: PR Labels

on:
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize ]

jobs:
  pr_labels:
    name: 🏭 Verify
    runs-on: ubuntu-latest
    steps:
      - name: 🏷 Verify PR has a valid label
        uses: jesusvasquez333/verify-pr-label-action@v1.4.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          valid-labels: >-
            priority-critical, priority-high, priority-medium, priority-low
            scope-documentation, scope-enhancement, scope-bug, scope-performance,
            scope-new-feature, scope-security
          invalid-labels: >-
            version-major, version-minor, version-patch,
            status-duplicate, status-in-progress, status-stale, 
            status-incomplete, status-invalid, status-wontfix,
            good first issue, help-wanted
          disable-reviews: true
