name: Release

on:
  workflow_dispatch:
    inputs:
      skip_release_file:
        type: boolean
        required: false
        default: true
        description: Skip create release file
      release_file_name:
        required: true
        default: 'release'
      release_directory:
        required: true
        default: '.'
      version:
        required: false
        default: ''
      skip_changelog:
        type: boolean
        default: true
        description: Skip generate changelog
      create_pr_for_branch:
        required: false
        default: 'main'
        description: Target branch? empty for skip.

permissions:
  contents: write
  pull-requests: write

jobs:
  default:
    runs-on: ubuntu-latest

    # Limit branch:
    if: github.ref == 'refs/heads/dev'
    # Or
    #if: github.ref != 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Print inputs
        run: |
          echo "skip_release_file: ${{ inputs.skip_release_file }}"
          echo "release_file_name: ${{ inputs.release_file_name }}"
          echo "release_directory: ${{ inputs.release_directory }}"
          echo "skip_changelog: ${{ inputs.skip_changelog }}"
          echo "version: ${{ inputs.version }}"
          echo "create_pr_for_branch: ${{ inputs.create_pr_for_branch }}"
          echo "Current Branch: $(git rev-parse --abbrev-ref HEAD)"

      - name: Release
        uses: Payadel/release-sv-action@v0.2.1
        id: release
        with:
          version: ${{ inputs.version }}
          skip-changelog: ${{ inputs.skip_changelog }}
          skip-release-file: ${{ inputs.skip_release_file }}
          release-directory: ${{ inputs.release_directory }}
          release-file-name: ${{ inputs.release_file_name }}
          create-pr-for-branch: ${{ inputs.create_pr_for_branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: '${{ steps.release.outputs.releaseFileName }}'
          allowUpdates: true
          bodyFile: "CHANGELOG.md"
          tag: 'v${{ steps.release.outputs.version }}'
